### PR TITLE
Add reset command

### PR DESCRIPTION
**Pull request by Fishymobile**
Added reset command as per issue #130

### CODE REVIEW

**Comment by haakonnessjoen** [comment]
Thanks! But your indenting is all over the place. Check that you are using TAB's for indenting. But even the one line having tab's is wrong. So something weird are going on in your editor, if you are not seeing it?

**Comment by Fishymobile** [comment]
Ah okay sorry about that. First time doing anything like this. I'll try a
different editor (using brackets right now).

So just to be clear I should fix the indentations, re-commit, then submit
another pull request?

**Comment by Fishymobile** [comment]
Awesome thank you!

**Comment by Fishymobile** [comment]
Please let me know if there are any issues with this. (Still learning)

**Comment by haakonnessjoen** [comment]
I will merge this, but it will not be included in the 1.1.1 release, so it will not get built before v1.1.1 is released.

**Comment by Fishymobile** [comment]
understood. Thank you!

**Pull request merged**
